//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRL_Portal_API.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SLA for actor.
        /// </summary>
        internal static string DeleteSLAForActor {
            get {
                return ResourceManager.GetString("DeleteSLAForActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SLA could not be deleted as it is in use.
        /// </summary>
        internal static string DeleteSLAForActorHeader {
            get {
                return ResourceManager.GetString("DeleteSLAForActorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SSCC.
        /// </summary>
        internal static string SaveSSCC {
            get {
                return ResourceManager.GetString("SaveSSCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following detail(&apos;s) of SSCC could not be saved:.
        /// </summary>
        internal static string SaveSSCCHeader {
            get {
                return ResourceManager.GetString("SaveSSCCHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Order(&apos;s).
        /// </summary>
        internal static string ValidateMultipleOrder {
            get {
                return ResourceManager.GetString("ValidateMultipleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following order(&apos;s) could not be validated: .
        /// </summary>
        internal static string ValidateMultipleOrderHeader {
            get {
                return ResourceManager.GetString("ValidateMultipleOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate SSCC(&apos;s).
        /// </summary>
        internal static string ValidateMultipleSSCC {
            get {
                return ResourceManager.GetString("ValidateMultipleSSCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following SSCC(&apos;s) could not be validated: .
        /// </summary>
        internal static string ValidateMultipleSSCCHeader {
            get {
                return ResourceManager.GetString("ValidateMultipleSSCCHeader", resourceCulture);
            }
        }
    }
}
