//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT
    {
        public int AUDIT_ID { get; set; }
        public string UPDATE_TYPE { get; set; }
        public string TABLE_NAME { get; set; }
        public string PRIMARY_KEY_FIELD { get; set; }
        public string PRIMARY_KEY_VALUE { get; set; }
        public string FIELD_NAME { get; set; }
        public string OLD_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string LOAD_MESSAGE_STATUS_ID { get; set; }
    }
}
