//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_SOURCE_REFERENCE_SLRS_NEW
    {
        public decimal SOURCE_REFERENCE_ID { get; set; }
        public Nullable<decimal> SOURCE_REFERENCE_TYPE_ID { get; set; }
        public string SOURCE_REFERENCE_TYPE_NAME { get; set; }
        public Nullable<decimal> BATCH_REGISTRATION_DATE { get; set; }
        public string BATCH_REGISTRATION_TIME { get; set; }
        public Nullable<decimal> SOURCE_REFERENCE_STATUS_ID { get; set; }
        public string SOURCE_REFERENCE_STATUS_NAME { get; set; }
        public Nullable<decimal> FILE_SEQUENCE_NR { get; set; }
        public Nullable<int> FILE_REFERENCE_NR { get; set; }
        public Nullable<decimal> CPF_TRA_ITEM_OUT_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public string FILE_DESTINATION { get; set; }
    }
}
