//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_SLRS_RCM415_SSCC
    {
        public string MESSAGE_LINE { get; set; }
        public int MESSAGE_TYPE_ID { get; set; }
        public string MESSAGE_TYPE_NAME { get; set; }
        public string MESSAGE_SORT { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> SOURCE_REFERENCE_ID { get; set; }
    }
}
