//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPF_410_AGGREGATED_ACTOR_CODE
    {
        public string ACTOR_COLUMN_CODE { get; set; }
        public decimal ACTOR_CODE { get; set; }
    }
}
