//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVIATION_BY_RETAILER
    {
        public int DEVIATION_BY_RETIALER_ID { get; set; }
        public int RETAILER_CHAIN_ID { get; set; }
        public long LOAD_UNIT_CONDITION_ID { get; set; }
    
        public virtual LOAD_UNIT_CONDITION LOAD_UNIT_CONDITION { get; set; }
        public virtual RETAILER_CHAIN RETAILER_CHAIN { get; set; }
    }
}
