//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESOFT_API_RCM500
    {
        public decimal ESOFT_API_RCM500_ID { get; set; }
        public decimal CPF_TRA_ITEM_IN_ID { get; set; }
        public Nullable<decimal> CPF_TRA_ITEM_OUT_ID { get; set; }
        public string CPF_ITEM_IN_CODE { get; set; }
        public decimal MESSAGE_STATUS_ID { get; set; }
        public string SENDER_GLN { get; set; }
        public string RECEIVER_GLN { get; set; }
        public string DOCUMENT_DATE { get; set; }
        public string REGISTRATION_DATE { get; set; }
        public string REGISTRATION_TIME { get; set; }
        public string GLOBAL_TYPE { get; set; }
        public string CUSTOMER_REFERENCE { get; set; }
        public string FIN_PARTNER_GLN { get; set; }
        public string FROM_GLN { get; set; }
        public string TO_GLN { get; set; }
        public string TRANSPORTER_NAME { get; set; }
        public string TRANSPORT_VEHICLE_LICENCE_PLATE { get; set; }
        public string REMARKS { get; set; }
        public string PACKING_EAN { get; set; }
        public string PACKING_QUANTITY { get; set; }
        public string LOGISTIC_VARIETY { get; set; }
        public string STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENABLED { get; set; }
        public string CONTENT { get; set; }
        public string CUSTOMER_REFERENCE_DETAIL { get; set; }
        public Nullable<decimal> CUSTOMER_REFERENCE_UNIQUE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> C_SENDER_ID { get; set; }
        public Nullable<decimal> C_FIN_PARTNER_ID { get; set; }
        public Nullable<decimal> C_FROM_ID { get; set; }
        public Nullable<decimal> C_TO_ID { get; set; }
        public Nullable<int> RCM_500_status_ID { get; set; }
    }
}
