//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_MESSAGE_UPDATE_STATUS_2
    {
        public string SSCC { get; set; }
        public long TRA_ITEM_IN_ID { get; set; }
        public Nullable<int> COUNTED_SSCC { get; set; }
        public int NUMBER_SSCC_ON_ORDER { get; set; }
    }
}
