//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT_SSCC_MANAGEMENT
    {
        public string ACTOR { get; set; }
        public string LOAD_UNIT { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string ORDERED_BY { get; set; }
        public Nullable<bool> CARDBORD_BOX { get; set; }
        public string ACTOR_DELIVERY { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> SSCC_ORDER_ID_ACCESS { get; set; }
        public Nullable<int> LOAD_MESSAGE_STATUS_ID { get; set; }
        public long ID { get; set; }
    }
}
