//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERFACING
    {
        public int INTERFACING_ID { get; set; }
        public Nullable<int> RETAILER_CHAIN_ID { get; set; }
        public Nullable<int> ACTOR_ID { get; set; }
        public Nullable<int> ACTOR_TYPE_ID { get; set; }
        public Nullable<bool> RCM500 { get; set; }
        public Nullable<bool> RCM419 { get; set; }
        public Nullable<bool> RCM415 { get; set; }
        public bool UNPLANNED_ORDERS { get; set; }
        public bool RCM410 { get; set; }
        public bool SEND_ARRIVAL_CONFIRMATION { get; set; }
        public bool SEND_RECEIPT_CONFIRMATION { get; set; }
    }
}
