//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_UNIT_CONDITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAD_UNIT_CONDITION()
        {
            this.DEVIATION_BY_RETAILER = new HashSet<DEVIATION_BY_RETAILER>();
            this.LINK_TRANSACTION_LOAD_UNIT_CONDITION = new HashSet<LINK_TRANSACTION_LOAD_UNIT_CONDITION>();
            this.LOAD_UNIT_CONDITION_TRANSLATION = new HashSet<LOAD_UNIT_CONDITION_TRANSLATION>();
        }
    
        public long LOAD_UNIT_CONDITION_ID { get; set; }
        public string LOAD_UNIT_CONDITION_CODE { get; set; }
        public int LOAD_UNIT_CONDITION_SORT { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<bool> CRITICAL_MISSING_SEU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVIATION_BY_RETAILER> DEVIATION_BY_RETAILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_TRANSACTION_LOAD_UNIT_CONDITION> LINK_TRANSACTION_LOAD_UNIT_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_UNIT_CONDITION_TRANSLATION> LOAD_UNIT_CONDITION_TRANSLATION { get; set; }
    }
}
