//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_CARRIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAD_CARRIER()
        {
            this.LOAD_CARRIER_TRANSLATION = new HashSet<LOAD_CARRIER_TRANSLATION>();
            this.LOAD_UNIT = new HashSet<LOAD_UNIT>();
        }
    
        public int LOAD_CARRIER_ID { get; set; }
        public string LOAD_CARRIER_CODE { get; set; }
        public int LOAD_CARRIER_SORT { get; set; }
        public int LOAD_CARRIER_LENGTH { get; set; }
        public int LOAD_CARRIER_WIDTH { get; set; }
        public int LOAD_CARRIER_HEIGHT { get; set; }
        public decimal LOAD_CARRIER_VOLUME { get; set; }
        public int LOAD_CARRIER_WEIGHT { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<decimal> LOAD_CARRIER_SURFACE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_CARRIER_TRANSLATION> LOAD_CARRIER_TRANSLATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_UNIT> LOAD_UNIT { get; set; }
    }
}
