//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_UNIT_SLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAD_UNIT_SLA()
        {
            this.SSCC_ORDER = new HashSet<SSCC_ORDER>();
            this.TRANSACTION = new HashSet<TRANSACTION>();
        }
    
        public int LOAD_UNIT_SLA_ID { get; set; }
        public string LOAD_UNIT_SLA_CODE { get; set; }
        public int LOAD_UNIT_ID { get; set; }
        public int ACTOR_ID { get; set; }
        public Nullable<int> THEORETICAL_WEIGHT { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string STANDARD_SLA_ID { get; set; }
        public Nullable<decimal> RTI_ACCEPTANCE { get; set; }
    
        public virtual ACTOR_REFERENCE ACTOR_REFERENCE { get; set; }
        public virtual LOAD_UNIT LOAD_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSCC_ORDER> SSCC_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTION { get; set; }
    }
}
