//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_UNIT_SUB_CONDITION
    {
        public int LOAD_UNIT_SUB_CONDITION_ID { get; set; }
        public int LOAD_UNIT_CONDITION_ID { get; set; }
        public string LOAD_UNIT_CONDITION_SUB_CODE { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
