//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOVEXX
    {
        public long SSCC_ORDER_ID { get; set; }
        public string HEADER { get; set; }
        public string LBL_SENDER { get; set; }
        public string SENDER { get; set; }
        public string LBL_RECIPIENT { get; set; }
        public string RECIPENT { get; set; }
        public string SSCC { get; set; }
        public string LBL_STANDARD { get; set; }
        public string LBL_STACKS { get; set; }
        public string STACKS { get; set; }
        public string LBL_LAYERS { get; set; }
        public string LAYERS { get; set; }
        public string LBL_SORTING { get; set; }
        public string SORTING { get; set; }
        public string LBL_CARRIER { get; set; }
        public string CARRIER { get; set; }
        public string REMARK { get; set; }
        public string HEADER2 { get; set; }
        public string SEU { get; set; }
    }
}
