//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_TRANSACTION_TEMP_RECEIPTS
    {
        public int REF_TRANSACTION_TEMP_RECEIPTS_ID { get; set; }
        public decimal ORDER_ID { get; set; }
        public decimal TRANSACTION_ID { get; set; }
        public decimal TRANSACTION_LINE_ID { get; set; }
        public string TRA_REFERENCE { get; set; }
        public Nullable<decimal> BASIC_TRANSACTION_TYPE_ID { get; set; }
        public Nullable<decimal> TRANSACTION_TYPE_ID { get; set; }
        public Nullable<decimal> TEMP_RECEIPT_DATE { get; set; }
        public Nullable<decimal> NUMBER_OF_PPC { get; set; }
        public Nullable<decimal> RECEIPT_STATUS_ID { get; set; }
        public Nullable<decimal> NUMBER_OF_PACKING { get; set; }
    }
}
