//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_CALENDAR_DAY
    {
        public decimal DAY_KEY { get; set; }
        public Nullable<System.DateTime> DAY_DATE { get; set; }
        public string DAY_LABEL { get; set; }
        public string DAY_NAME_SHORT { get; set; }
        public string DAY_NAME { get; set; }
        public Nullable<int> DAY_IN_WEEK { get; set; }
        public Nullable<int> DAY_IN_MONTH { get; set; }
        public Nullable<int> DAY_IN_YEAR { get; set; }
        public string DAY_LAST_DAY_MONTH_YN { get; set; }
        public Nullable<System.DateTime> DAY_LAST_DAY_MONTH { get; set; }
        public Nullable<int> DAY_vs_CURRENT_DAY_IN_CALENDAR { get; set; }
        public Nullable<int> DAY_vs_CURRENT_DAY_IN_YEAR { get; set; }
        public decimal WEEK_KEY { get; set; }
        public string WEEK_LABEL { get; set; }
        public Nullable<int> WEEK_NR { get; set; }
        public string WEEK_NAME_SHORT { get; set; }
        public string WEEK_NAME { get; set; }
        public Nullable<int> WEEK_vs_CURRENT_WEEK_IN_CALENDAR { get; set; }
        public Nullable<int> WEEK_vs_CURRENT_WEEK_IN_YEAR { get; set; }
        public decimal WEEK_KEY_DLL { get; set; }
        public string WEEK_LABEL_DLL { get; set; }
        public Nullable<int> WEEK_NR_DLL { get; set; }
        public string WEEK_NAME_SHORT_DLL { get; set; }
        public string WEEK_NAME_DLL { get; set; }
        public decimal MONTH_KEY { get; set; }
        public string MONTH_LABEL { get; set; }
        public Nullable<int> MONTH_NR { get; set; }
        public string MONTH_NAME_SHORT { get; set; }
        public string MONTH_NAME { get; set; }
        public Nullable<int> MONTH_vs_CURRENT_MONTH_IN_CALENDAR { get; set; }
        public Nullable<int> MONTH_vs_CURRENT_MONTH_IN_YEAR { get; set; }
        public decimal QUARTER_KEY { get; set; }
        public string QUARTER_LABEL { get; set; }
        public Nullable<int> QUARTER_NR { get; set; }
        public string QUARTER_NAME_SHORT { get; set; }
        public string QUARTER_NAME { get; set; }
        public Nullable<int> QUARTER_vs_CURRENT_QUARTER_IN_CALENDAR { get; set; }
        public Nullable<int> QUARTER_vs_CURRENT_QUARTER_IN_YEAR { get; set; }
        public decimal YEAR_KEY { get; set; }
        public Nullable<int> YEAR_NR { get; set; }
        public string YEAR_LABEL { get; set; }
        public string YEAR_NAME { get; set; }
        public Nullable<int> YEAR_vs_CURRENT_YEAR_IN_CALENDAR { get; set; }
    }
}
