//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_ARTICLE_PACKING
    {
        public decimal ID_PACKING { get; set; }
        public decimal PAC_EPS_CODE { get; set; }
        public string PAC_PACKING_NAME { get; set; }
        public string PAC_PACKING_SHORT_NAME { get; set; }
        public string PAC_ABBREVIATION { get; set; }
        public decimal PAC_EAN_CODE { get; set; }
        public decimal PAC_COST_BEARER { get; set; }
        public Nullable<decimal> PAC_SORTING_NUMBER { get; set; }
        public decimal PACKING_TYPE_ID { get; set; }
        public string PACKING_TYPE { get; set; }
        public decimal PACKING_CLASS_1_ID { get; set; }
        public string PACKING_CLASS_1 { get; set; }
        public decimal PACKING_CLASS_2_ID { get; set; }
        public string PACKING_CLASS_2 { get; set; }
        public decimal PACKING_CLASS_3_ID { get; set; }
        public Nullable<decimal> PACKING_CLASS_3_LABEL_ID { get; set; }
        public string PACKING_CLASS_3_LABEL { get; set; }
        public string PACKING_CLASS_3 { get; set; }
        public Nullable<decimal> PACKING_CLASS_4_ID { get; set; }
        public string PACKING_CLASS_4 { get; set; }
        public decimal PAC_VPFQ_IN { get; set; }
        public decimal PAC_VPFQ_OUT { get; set; }
        public Nullable<decimal> PAC_VPFQ_POOL_IN { get; set; }
        public Nullable<decimal> PAC_VPFQ_POOL_OUT { get; set; }
        public decimal ACTIVE { get; set; }
        public Nullable<decimal> DELETED { get; set; }
        public decimal PAC_HEIGHT_FOLDED_IN { get; set; }
        public decimal PAC_HEIGHT_FOLDED_OUT { get; set; }
        public decimal PAC_WEIGHT { get; set; }
        public decimal PAC_LENGTH { get; set; }
        public decimal PAC_WIDTH { get; set; }
        public decimal PAC_WEIGHT_QUANTITY { get; set; }
        public Nullable<decimal> PAC_MAX_FLOOR_CAPACITY { get; set; }
        public decimal PAC_EXCHANGE { get; set; }
        public decimal MATERIAL_ID { get; set; }
        public decimal PAC_CONVERSION_IN { get; set; }
        public decimal PAC_CONVERSION_OUT { get; set; }
        public decimal PAC_STACKING_EDGE { get; set; }
        public decimal PAC_MAX_ORD_QUANTITY { get; set; }
        public string COMMERCIAL_YN { get; set; }
        public Nullable<decimal> FLOOR_TYPE_2D_ID { get; set; }
        public string FLOOR_TYPE_2D { get; set; }
        public Nullable<decimal> FLOOR_TYPE_3D_ID { get; set; }
        public string FLOOR_TYPE_3D { get; set; }
        public Nullable<decimal> TRSP_FLOOR_TYPE_ID { get; set; }
        public string TRSP_FLOOR_TYPE { get; set; }
        public decimal PACKING_TYPE_SORT { get; set; }
        public decimal PACKING_CLASS_1_SORT { get; set; }
        public decimal PACKING_CLASS_2_SORT { get; set; }
        public decimal PACKING_CLASS_3_SORT { get; set; }
        public decimal PACKING_CLASS_3_LABEL_SORT { get; set; }
        public decimal PACKING_CLASS_4_SORT { get; set; }
        public decimal TRSP_FLOOR_TYPE_SORT { get; set; }
        public string LOGISTIC_YN { get; set; }
        public Nullable<decimal> SFPL_FACTOR { get; set; }
        public Nullable<decimal> SFTL_FACTOR { get; set; }
        public Nullable<decimal> SFPL_FACTOR_Handling { get; set; }
        public Nullable<decimal> WASHING_RECALC_FACTOR { get; set; }
        public Nullable<decimal> PAC_CLASS_3_LABEL_LEVEL_1_ID { get; set; }
        public string PAC_CLASS_3_LABEL_LEVEL_1 { get; set; }
        public Nullable<decimal> PAC_CLASS_3_LABEL_LEVEL_1_SORT { get; set; }
        public Nullable<decimal> PAC_CLASS_3_LABEL_LEVEL_2_ID { get; set; }
        public string PAC_CLASS_3_LABEL_LEVEL_2 { get; set; }
        public Nullable<decimal> PAC_CLASS_3_LABEL_LEVEL_2_SORT { get; set; }
        public Nullable<decimal> QTY_SEU_EQUIVALENT { get; set; }
    }
}
