//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_TRANSLATED
    {
        public int RTI_ID { get; set; }
        public decimal RTI_CODE { get; set; }
        public decimal RTI_HEIGHT { get; set; }
        public int RTI_LENGTH { get; set; }
        public int RTI_WIDTH { get; set; }
        public int RTI_WEIGHT { get; set; }
        public Nullable<decimal> RTI_VOLUME { get; set; }
        public decimal QTY_SEU_EQUIVALENT { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public int RTI_TRANSLATION_ID { get; set; }
        public string LANGUAGE { get; set; }
        public string RTI_NAME_SHORT { get; set; }
        public string RTI_NAME { get; set; }
        public Nullable<decimal> RTI_EAN { get; set; }
        public string RTI_COLOR { get; set; }
        public Nullable<decimal> MATCHING_UNKNOWN_TRAY { get; set; }
        public Nullable<int> REPORT_RTI_SORTING { get; set; }
    }
}
