//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_ACCEPTANCE
    {
        public int RTI_ID { get; set; }
        public decimal RTI_CODE { get; set; }
        public decimal ACCEPTANCE_ID { get; set; }
    }
}
