//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BACKUP_SRL_20180613Entities : DbContext
    {
        public BACKUP_SRL_20180613Entities()
            : base("name=BACKUP_SRL_20180613Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTION> ACTION { get; set; }
        public virtual DbSet<ACTOR_LABEL_DETAILS> ACTOR_LABEL_DETAILS { get; set; }
        public virtual DbSet<ACTOR_REFERENCE> ACTOR_REFERENCE { get; set; }
        public virtual DbSet<ACTOR_TYPE> ACTOR_TYPE { get; set; }
        public virtual DbSet<AUDIT> AUDIT { get; set; }
        public virtual DbSet<CONTENT> CONTENT { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS> CPF_SOURCE_REFERENCE_SLRS { get; set; }
        public virtual DbSet<DEPOT_LABEL> DEPOT_LABEL { get; set; }
        public virtual DbSet<DEVIATION_BY_RETAILER> DEVIATION_BY_RETAILER { get; set; }
        public virtual DbSet<ERROR> ERROR { get; set; }
        public virtual DbSet<ERROR_HANDLING> ERROR_HANDLING { get; set; }
        public virtual DbSet<ERROR_HANDLING_ARCHIVE> ERROR_HANDLING_ARCHIVE { get; set; }
        public virtual DbSet<ERROR_TRANSLATION> ERROR_TRANSLATION { get; set; }
        public virtual DbSet<ESOFT_API_RCM500> ESOFT_API_RCM500 { get; set; }
        public virtual DbSet<INPUT_SSCC_MANAGEMENT> INPUT_SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<INTERFACING> INTERFACING { get; set; }
        public virtual DbSet<LATE_TRANSACTIONS> LATE_TRANSACTIONS { get; set; }
        public virtual DbSet<LINK_TRANSACTION_LOAD_UNIT_CONDITION> LINK_TRANSACTION_LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_CARRIER> LOAD_CARRIER { get; set; }
        public virtual DbSet<LOAD_CARRIER_TRANSLATION> LOAD_CARRIER_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT> LOAD_UNIT { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION> LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION_TRANSLATION> LOAD_UNIT_CONDITION_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT_SLA> LOAD_UNIT_SLA { get; set; }
        public virtual DbSet<LOAD_UNIT_SUB_CONDITION> LOAD_UNIT_SUB_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_TRANSLATION> LOAD_UNIT_TRANSLATION { get; set; }
        public virtual DbSet<PICTURE_EVIDENCE> PICTURE_EVIDENCE { get; set; }
        public virtual DbSet<REF_ORDER> REF_ORDER { get; set; }
        public virtual DbSet<REF_TRANSACTION_TEMP_RECEIPTS> REF_TRANSACTION_TEMP_RECEIPTS { get; set; }
        public virtual DbSet<REPORTING_ACTOR_TYPE> REPORTING_ACTOR_TYPE { get; set; }
        public virtual DbSet<RETAILER_CHAIN> RETAILER_CHAIN { get; set; }
        public virtual DbSet<RT_TYPE> RT_TYPE { get; set; }
        public virtual DbSet<RTI> RTI { get; set; }
        public virtual DbSet<RTI_ACCEPTANCE> RTI_ACCEPTANCE { get; set; }
        public virtual DbSet<RTI_TRANSLATION> RTI_TRANSLATION { get; set; }
        public virtual DbSet<SHIPMENT> SHIPMENT { get; set; }
        public virtual DbSet<SORTING_STATUS> SORTING_STATUS { get; set; }
        public virtual DbSet<SORTING_STATUS_TRANSLATION> SORTING_STATUS_TRANSLATION { get; set; }
        public virtual DbSet<SSCC> SSCC { get; set; }
        public virtual DbSet<SSCC_DEL> SSCC_DEL { get; set; }
        public virtual DbSet<SSCC_MANAGEMENT> SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<SSCC_ORDER> SSCC_ORDER { get; set; }
        public virtual DbSet<SSCC_RTI_DETAILS> SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<SSCC_RTI_GRAI> SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<STANDARD_DISTRIBUTION> STANDARD_DISTRIBUTION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIMEONSITE> TIMEONSITE { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTION { get; set; }
        public virtual DbSet<TRANSACTION_DEL> TRANSACTION_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS> TRANSACTION_SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_DEL> TRANSACTION_SSCC_RTI_DETAILS_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF> TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_GRAI> TRANSACTION_SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<TRANSACTION_SUBTYPES> TRANSACTION_SUBTYPES { get; set; }
        public virtual DbSet<TRANSLATION_DETAILS> TRANSLATION_DETAILS { get; set; }
        public virtual DbSet<XML_EXPORT_MESSAGES> XML_EXPORT_MESSAGES { get; set; }
        public virtual DbSet<Z_CHANGES_TO_DATABASE> Z_CHANGES_TO_DATABASE { get; set; }
        public virtual DbSet<Z_LOAD_MESSAGE_STATUS> Z_LOAD_MESSAGE_STATUS { get; set; }
        public virtual DbSet<Z_SSCC_NUMBERS> Z_SSCC_NUMBERS { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_NUMBER> Z_SSCC_ORDER_NUMBER { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_RETAILER_DETAILS> Z_SSCC_ORDER_RETAILER_DETAILS { get; set; }
        public virtual DbSet<Z_STG_XML_ANOMALIES> Z_STG_XML_ANOMALIES { get; set; }
        public virtual DbSet<Z_STG_XML_CONTENT> Z_STG_XML_CONTENT { get; set; }
        public virtual DbSet<Z_STG_XML_COUNTING> Z_STG_XML_COUNTING { get; set; }
        public virtual DbSet<Z_STG_XML_DATA> Z_STG_XML_DATA { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD> Z_STG_XML_LOAD { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD_CARRIER> Z_STG_XML_LOAD_CARRIER { get; set; }
        public virtual DbSet<Z_STG_XML_ORDER> Z_STG_XML_ORDER { get; set; }
        public virtual DbSet<Z_STG_XML_PICTURES> Z_STG_XML_PICTURES { get; set; }
        public virtual DbSet<Z_STG_XML_SHIPMENT> Z_STG_XML_SHIPMENT { get; set; }
        public virtual DbSet<Z_STG_XML_TIMEONSITE> Z_STG_XML_TIMEONSITE { get; set; }
        public virtual DbSet<Z_STG_XML_TRANSACTION> Z_STG_XML_TRANSACTION { get; set; }
        public virtual DbSet<Z_VALIDATION> Z_VALIDATION { get; set; }
        public virtual DbSet<CPF_410_AGGREGATED_ACTOR_CODE> CPF_410_AGGREGATED_ACTOR_CODE { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_NEW> CPF_SOURCE_REFERENCE_SLRS_NEW { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM410> CPF_SOURCE_REFERENCE_SLRS_RCM410 { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM415> CPF_SOURCE_REFERENCE_SLRS_RCM415 { get; set; }
        public virtual DbSet<PARAMETER_SRLS> PARAMETER_SRLS { get; set; }
        public virtual DbSet<PARAMETER_SRLS_NEW> PARAMETER_SRLS_NEW { get; set; }
        public virtual DbSet<REF_ORDER_UPSERT> REF_ORDER_UPSERT { get; set; }
        public virtual DbSet<RTI_DATASET> RTI_DATASET { get; set; }
        public virtual DbSet<RUNNING_JOB_CHECK> RUNNING_JOB_CHECK { get; set; }
        public virtual DbSet<CPF_SLRS_RCM410_SSCC> CPF_SLRS_RCM410_SSCC { get; set; }
        public virtual DbSet<CPF_SLRS_RCM410_SSCC_OUD> CPF_SLRS_RCM410_SSCC_OUD { get; set; }
        public virtual DbSet<CPF_SLRS_RCM415_SSCC> CPF_SLRS_RCM415_SSCC { get; set; }
        public virtual DbSet<CPF_SLRS_RCM419_SSCC> CPF_SLRS_RCM419_SSCC { get; set; }
        public virtual DbSet<CPF_SLRS_RCM419_SSCC_NEW> CPF_SLRS_RCM419_SSCC_NEW { get; set; }
        public virtual DbSet<EXPORT_MESSAGE_UPDATE_STATUS_2> EXPORT_MESSAGE_UPDATE_STATUS_2 { get; set; }
        public virtual DbSet<EXPORT_MESSAGE_UPDATE_STATUS_2_SUM> EXPORT_MESSAGE_UPDATE_STATUS_2_SUM { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION_TRANSLATED> LOAD_UNIT_CONDITION_TRANSLATED { get; set; }
        public virtual DbSet<NOVEXX> NOVEXX { get; set; }
        public virtual DbSet<RCM410_SSCC_VW> RCM410_SSCC_VW { get; set; }
        public virtual DbSet<REF_ARTICLE_PACKING> REF_ARTICLE_PACKING { get; set; }
        public virtual DbSet<REF_CALENDAR_DAY> REF_CALENDAR_DAY { get; set; }
        public virtual DbSet<REF_CALENDAR_MONTH> REF_CALENDAR_MONTH { get; set; }
        public virtual DbSet<REF_CALENDAR_WEEK> REF_CALENDAR_WEEK { get; set; }
        public virtual DbSet<REF_PARAMETER_OUD> REF_PARAMETER_OUD { get; set; }
        public virtual DbSet<RTI_TRANSLATED> RTI_TRANSLATED { get; set; }
        public virtual DbSet<SLA_UNIT_INFO_DETAILS> SLA_UNIT_INFO_DETAILS { get; set; }
        public virtual DbSet<SSCC_ORDER_OVERVIEW> SSCC_ORDER_OVERVIEW { get; set; }
        public virtual DbSet<VW_AUTOMATIC_SLA_MATCH> VW_AUTOMATIC_SLA_MATCH { get; set; }
        public virtual DbSet<VW_CI_WITHOUT_INBOUND> VW_CI_WITHOUT_INBOUND { get; set; }
        public virtual DbSet<vw_DEPOT_LABEL> vw_DEPOT_LABEL { get; set; }
        public virtual DbSet<VW_ERROR_DOUBLE_COUNTING> VW_ERROR_DOUBLE_COUNTING { get; set; }
        public virtual DbSet<VW_INBOUND_WITHOUT_CI> VW_INBOUND_WITHOUT_CI { get; set; }
        public virtual DbSet<VW_MONO_SSCC> VW_MONO_SSCC { get; set; }
        public virtual DbSet<vw_RTG_DATASET> vw_RTG_DATASET { get; set; }
        public virtual DbSet<vw_RTG_DATASET_MT> vw_RTG_DATASET_MT { get; set; }
        public virtual DbSet<vw_RTI_DATASET> vw_RTI_DATASET { get; set; }
        public virtual DbSet<vw_RTI_DATASET_MT> vw_RTI_DATASET_MT { get; set; }
        public virtual DbSet<vw_RTI_DATASET_X> vw_RTI_DATASET_X { get; set; }
        public virtual DbSet<VW_SSCC_CI> VW_SSCC_CI { get; set; }
        public virtual DbSet<VW_SSCC_MULTI_LOAD_CARRIER> VW_SSCC_MULTI_LOAD_CARRIER { get; set; }
        public virtual DbSet<VW_SSCC_VALIDATED> VW_SSCC_VALIDATED { get; set; }
        public virtual DbSet<VW_SSCC_VALIDATED_MT> VW_SSCC_VALIDATED_MT { get; set; }
        public virtual DbSet<Z_RPT_PROCESS_QTY> Z_RPT_PROCESS_QTY { get; set; }
        public virtual DbSet<Z_STG_XML_DV_ANOMALIES> Z_STG_XML_DV_ANOMALIES { get; set; }
        public virtual DbSet<Z_STG_XML_DV_CONTENT> Z_STG_XML_DV_CONTENT { get; set; }
        public virtual DbSet<Z_STG_XML_DV_COUNTING> Z_STG_XML_DV_COUNTING { get; set; }
        public virtual DbSet<Z_STG_XML_DV_LOAD> Z_STG_XML_DV_LOAD { get; set; }
        public virtual DbSet<Z_STG_XML_DV_LOAD_CARRIER> Z_STG_XML_DV_LOAD_CARRIER { get; set; }
        public virtual DbSet<Z_STG_XML_DV_ORDER> Z_STG_XML_DV_ORDER { get; set; }
        public virtual DbSet<Z_STG_XML_DV_PICTURES> Z_STG_XML_DV_PICTURES { get; set; }
        public virtual DbSet<Z_STG_XML_DV_SHIPMENT> Z_STG_XML_DV_SHIPMENT { get; set; }
        public virtual DbSet<Z_STG_XML_DV_TIMEONSITE> Z_STG_XML_DV_TIMEONSITE { get; set; }
        public virtual DbSet<Z_STG_XML_DV_TRANSACTION> Z_STG_XML_DV_TRANSACTION { get; set; }
        public virtual DbSet<temp_TRANSACTION_2018> temp_TRANSACTION_2018 { get; set; }
        public virtual DbSet<temp_TRANSACTION_SSCC_RTI_DETAILS_2018> temp_TRANSACTION_SSCC_RTI_DETAILS_2018 { get; set; }
        public virtual DbSet<temp_Z_STG_XML_DATA_2018> temp_Z_STG_XML_DATA_2018 { get; set; }
    
        public virtual ObjectResult<GetOrderDetail_Result> GetOrderDetail(Nullable<int> oRDER_ID, Nullable<int> rETAILER_CHAIN_ID)
        {
            var oRDER_IDParameter = oRDER_ID.HasValue ?
                new ObjectParameter("ORDER_ID", oRDER_ID) :
                new ObjectParameter("ORDER_ID", typeof(int));
    
            var rETAILER_CHAIN_IDParameter = rETAILER_CHAIN_ID.HasValue ?
                new ObjectParameter("RETAILER_CHAIN_ID", rETAILER_CHAIN_ID) :
                new ObjectParameter("RETAILER_CHAIN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDetail_Result>("GetOrderDetail", oRDER_IDParameter, rETAILER_CHAIN_IDParameter);
        }
    }
}
