//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BACKUP_SRL_20180613Entities1 : DbContext
    {
        public BACKUP_SRL_20180613Entities1()
            : base("name=BACKUP_SRL_20180613Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTION> ACTION { get; set; }
        public virtual DbSet<ACTOR_LABEL_DETAILS> ACTOR_LABEL_DETAILS { get; set; }
        public virtual DbSet<ACTOR_REFERENCE> ACTOR_REFERENCE { get; set; }
        public virtual DbSet<ACTOR_TYPE> ACTOR_TYPE { get; set; }
        public virtual DbSet<AUDIT> AUDIT { get; set; }
        public virtual DbSet<CONTENT> CONTENT { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS> CPF_SOURCE_REFERENCE_SLRS { get; set; }
        public virtual DbSet<DEPOT_LABEL> DEPOT_LABEL { get; set; }
        public virtual DbSet<DEVIATION_BY_RETAILER> DEVIATION_BY_RETAILER { get; set; }
        public virtual DbSet<ERROR> ERROR { get; set; }
        public virtual DbSet<ERROR_HANDLING> ERROR_HANDLING { get; set; }
        public virtual DbSet<ERROR_HANDLING_ARCHIVE> ERROR_HANDLING_ARCHIVE { get; set; }
        public virtual DbSet<ERROR_TRANSLATION> ERROR_TRANSLATION { get; set; }
        public virtual DbSet<ESOFT_API_RCM500> ESOFT_API_RCM500 { get; set; }
        public virtual DbSet<INPUT_SSCC_MANAGEMENT> INPUT_SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<INTERFACING> INTERFACING { get; set; }
        public virtual DbSet<LATE_TRANSACTIONS> LATE_TRANSACTIONS { get; set; }
        public virtual DbSet<LINK_TRANSACTION_LOAD_UNIT_CONDITION> LINK_TRANSACTION_LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_CARRIER> LOAD_CARRIER { get; set; }
        public virtual DbSet<LOAD_CARRIER_TRANSLATION> LOAD_CARRIER_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT> LOAD_UNIT { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION> LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION_TRANSLATION> LOAD_UNIT_CONDITION_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT_SLA> LOAD_UNIT_SLA { get; set; }
        public virtual DbSet<LOAD_UNIT_SUB_CONDITION> LOAD_UNIT_SUB_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_TRANSLATION> LOAD_UNIT_TRANSLATION { get; set; }
        public virtual DbSet<PICTURE_EVIDENCE> PICTURE_EVIDENCE { get; set; }
        public virtual DbSet<REF_ORDER> REF_ORDER { get; set; }
        public virtual DbSet<REF_TRANSACTION_TEMP_RECEIPTS> REF_TRANSACTION_TEMP_RECEIPTS { get; set; }
        public virtual DbSet<REPORTING_ACTOR_TYPE> REPORTING_ACTOR_TYPE { get; set; }
        public virtual DbSet<RETAILER_CHAIN> RETAILER_CHAIN { get; set; }
        public virtual DbSet<RT_TYPE> RT_TYPE { get; set; }
        public virtual DbSet<RTI> RTI { get; set; }
        public virtual DbSet<RTI_ACCEPTANCE> RTI_ACCEPTANCE { get; set; }
        public virtual DbSet<RTI_TRANSLATION> RTI_TRANSLATION { get; set; }
        public virtual DbSet<SHIPMENT> SHIPMENT { get; set; }
        public virtual DbSet<SORTING_STATUS> SORTING_STATUS { get; set; }
        public virtual DbSet<SORTING_STATUS_TRANSLATION> SORTING_STATUS_TRANSLATION { get; set; }
        public virtual DbSet<SSCC> SSCC { get; set; }
        public virtual DbSet<SSCC_DEL> SSCC_DEL { get; set; }
        public virtual DbSet<SSCC_MANAGEMENT> SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<SSCC_ORDER> SSCC_ORDER { get; set; }
        public virtual DbSet<SSCC_RTI_DETAILS> SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<SSCC_RTI_GRAI> SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<STANDARD_DISTRIBUTION> STANDARD_DISTRIBUTION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIMEONSITE> TIMEONSITE { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTION { get; set; }
        public virtual DbSet<TRANSACTION_DEL> TRANSACTION_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS> TRANSACTION_SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_DEL> TRANSACTION_SSCC_RTI_DETAILS_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF> TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_GRAI> TRANSACTION_SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<TRANSACTION_SUBTYPES> TRANSACTION_SUBTYPES { get; set; }
        public virtual DbSet<TRANSLATION_DETAILS> TRANSLATION_DETAILS { get; set; }
        public virtual DbSet<XML_EXPORT_MESSAGES> XML_EXPORT_MESSAGES { get; set; }
        public virtual DbSet<Z_CHANGES_TO_DATABASE> Z_CHANGES_TO_DATABASE { get; set; }
        public virtual DbSet<Z_LOAD_MESSAGE_STATUS> Z_LOAD_MESSAGE_STATUS { get; set; }
        public virtual DbSet<Z_SSCC_NUMBERS> Z_SSCC_NUMBERS { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_NUMBER> Z_SSCC_ORDER_NUMBER { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_RETAILER_DETAILS> Z_SSCC_ORDER_RETAILER_DETAILS { get; set; }
        public virtual DbSet<Z_STG_XML_ANOMALIES> Z_STG_XML_ANOMALIES { get; set; }
        public virtual DbSet<Z_STG_XML_CONTENT> Z_STG_XML_CONTENT { get; set; }
        public virtual DbSet<Z_STG_XML_COUNTING> Z_STG_XML_COUNTING { get; set; }
        public virtual DbSet<Z_STG_XML_DATA> Z_STG_XML_DATA { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD> Z_STG_XML_LOAD { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD_CARRIER> Z_STG_XML_LOAD_CARRIER { get; set; }
        public virtual DbSet<Z_STG_XML_ORDER> Z_STG_XML_ORDER { get; set; }
        public virtual DbSet<Z_STG_XML_PICTURES> Z_STG_XML_PICTURES { get; set; }
        public virtual DbSet<Z_STG_XML_SHIPMENT> Z_STG_XML_SHIPMENT { get; set; }
        public virtual DbSet<Z_STG_XML_TIMEONSITE> Z_STG_XML_TIMEONSITE { get; set; }
        public virtual DbSet<Z_STG_XML_TRANSACTION> Z_STG_XML_TRANSACTION { get; set; }
        public virtual DbSet<Z_VALIDATION> Z_VALIDATION { get; set; }
        public virtual DbSet<CPF_410_AGGREGATED_ACTOR_CODE> CPF_410_AGGREGATED_ACTOR_CODE { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_NEW> CPF_SOURCE_REFERENCE_SLRS_NEW { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM410> CPF_SOURCE_REFERENCE_SLRS_RCM410 { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM415> CPF_SOURCE_REFERENCE_SLRS_RCM415 { get; set; }
        public virtual DbSet<PARAMETER_SRLS> PARAMETER_SRLS { get; set; }
        public virtual DbSet<PARAMETER_SRLS_NEW> PARAMETER_SRLS_NEW { get; set; }
        public virtual DbSet<REF_ORDER_UPSERT> REF_ORDER_UPSERT { get; set; }
        public virtual DbSet<RTI_DATASET> RTI_DATASET { get; set; }
        public virtual DbSet<RUNNING_JOB_CHECK> RUNNING_JOB_CHECK { get; set; }
    
        public virtual ObjectResult<Nullable<int>> API_INSERT_CHANGE(string sSCC, Nullable<decimal> oRDER_NUMBER, Nullable<decimal> nEW_ORDER_NUMBER, Nullable<decimal> oLD_ACTOR, Nullable<decimal> nEW_ACTOR, Nullable<int> lOAD_MESSAGE_STATUS_ID, Nullable<System.DateTime> uPDATE_DATE, string uPDATE_USER, string oLD_LOAD_UNIT_CONDITION_CODE, string nEW_LOAD_UNIT_CONDITION_CODE, Nullable<int> oLD_QTY_RTI, Nullable<decimal> eSOFT_PACKING_ID, Nullable<int> nEW_QTY_RTI, string dELETE_SSCC, string oLD_SSCC, string nEW_SSCC, Nullable<long> tRA_ITEM_IN_ID, string sLA_CODE, string tIME, string vALIDATION, string oLD_LOAD_UNIT_CONDITION_SUB_CODE, string nEW_LOAD_UNIT_CONDITION_SUB_CODE, string vOID_SSCC, string oLD_LOAD_CARRIER_EAN, string nEW_LOAD_CARRIER_EAN)
        {
            var sSCCParameter = sSCC != null ?
                new ObjectParameter("SSCC", sSCC) :
                new ObjectParameter("SSCC", typeof(string));
    
            var oRDER_NUMBERParameter = oRDER_NUMBER.HasValue ?
                new ObjectParameter("ORDER_NUMBER", oRDER_NUMBER) :
                new ObjectParameter("ORDER_NUMBER", typeof(decimal));
    
            var nEW_ORDER_NUMBERParameter = nEW_ORDER_NUMBER.HasValue ?
                new ObjectParameter("NEW_ORDER_NUMBER", nEW_ORDER_NUMBER) :
                new ObjectParameter("NEW_ORDER_NUMBER", typeof(decimal));
    
            var oLD_ACTORParameter = oLD_ACTOR.HasValue ?
                new ObjectParameter("OLD_ACTOR", oLD_ACTOR) :
                new ObjectParameter("OLD_ACTOR", typeof(decimal));
    
            var nEW_ACTORParameter = nEW_ACTOR.HasValue ?
                new ObjectParameter("NEW_ACTOR", nEW_ACTOR) :
                new ObjectParameter("NEW_ACTOR", typeof(decimal));
    
            var lOAD_MESSAGE_STATUS_IDParameter = lOAD_MESSAGE_STATUS_ID.HasValue ?
                new ObjectParameter("LOAD_MESSAGE_STATUS_ID", lOAD_MESSAGE_STATUS_ID) :
                new ObjectParameter("LOAD_MESSAGE_STATUS_ID", typeof(int));
    
            var uPDATE_DATEParameter = uPDATE_DATE.HasValue ?
                new ObjectParameter("UPDATE_DATE", uPDATE_DATE) :
                new ObjectParameter("UPDATE_DATE", typeof(System.DateTime));
    
            var uPDATE_USERParameter = uPDATE_USER != null ?
                new ObjectParameter("UPDATE_USER", uPDATE_USER) :
                new ObjectParameter("UPDATE_USER", typeof(string));
    
            var oLD_LOAD_UNIT_CONDITION_CODEParameter = oLD_LOAD_UNIT_CONDITION_CODE != null ?
                new ObjectParameter("OLD_LOAD_UNIT_CONDITION_CODE", oLD_LOAD_UNIT_CONDITION_CODE) :
                new ObjectParameter("OLD_LOAD_UNIT_CONDITION_CODE", typeof(string));
    
            var nEW_LOAD_UNIT_CONDITION_CODEParameter = nEW_LOAD_UNIT_CONDITION_CODE != null ?
                new ObjectParameter("NEW_LOAD_UNIT_CONDITION_CODE", nEW_LOAD_UNIT_CONDITION_CODE) :
                new ObjectParameter("NEW_LOAD_UNIT_CONDITION_CODE", typeof(string));
    
            var oLD_QTY_RTIParameter = oLD_QTY_RTI.HasValue ?
                new ObjectParameter("OLD_QTY_RTI", oLD_QTY_RTI) :
                new ObjectParameter("OLD_QTY_RTI", typeof(int));
    
            var eSOFT_PACKING_IDParameter = eSOFT_PACKING_ID.HasValue ?
                new ObjectParameter("ESOFT_PACKING_ID", eSOFT_PACKING_ID) :
                new ObjectParameter("ESOFT_PACKING_ID", typeof(decimal));
    
            var nEW_QTY_RTIParameter = nEW_QTY_RTI.HasValue ?
                new ObjectParameter("NEW_QTY_RTI", nEW_QTY_RTI) :
                new ObjectParameter("NEW_QTY_RTI", typeof(int));
    
            var dELETE_SSCCParameter = dELETE_SSCC != null ?
                new ObjectParameter("DELETE_SSCC", dELETE_SSCC) :
                new ObjectParameter("DELETE_SSCC", typeof(string));
    
            var oLD_SSCCParameter = oLD_SSCC != null ?
                new ObjectParameter("OLD_SSCC", oLD_SSCC) :
                new ObjectParameter("OLD_SSCC", typeof(string));
    
            var nEW_SSCCParameter = nEW_SSCC != null ?
                new ObjectParameter("NEW_SSCC", nEW_SSCC) :
                new ObjectParameter("NEW_SSCC", typeof(string));
    
            var tRA_ITEM_IN_IDParameter = tRA_ITEM_IN_ID.HasValue ?
                new ObjectParameter("TRA_ITEM_IN_ID", tRA_ITEM_IN_ID) :
                new ObjectParameter("TRA_ITEM_IN_ID", typeof(long));
    
            var sLA_CODEParameter = sLA_CODE != null ?
                new ObjectParameter("SLA_CODE", sLA_CODE) :
                new ObjectParameter("SLA_CODE", typeof(string));
    
            var tIMEParameter = tIME != null ?
                new ObjectParameter("TIME", tIME) :
                new ObjectParameter("TIME", typeof(string));
    
            var vALIDATIONParameter = vALIDATION != null ?
                new ObjectParameter("VALIDATION", vALIDATION) :
                new ObjectParameter("VALIDATION", typeof(string));
    
            var oLD_LOAD_UNIT_CONDITION_SUB_CODEParameter = oLD_LOAD_UNIT_CONDITION_SUB_CODE != null ?
                new ObjectParameter("OLD_LOAD_UNIT_CONDITION_SUB_CODE", oLD_LOAD_UNIT_CONDITION_SUB_CODE) :
                new ObjectParameter("OLD_LOAD_UNIT_CONDITION_SUB_CODE", typeof(string));
    
            var nEW_LOAD_UNIT_CONDITION_SUB_CODEParameter = nEW_LOAD_UNIT_CONDITION_SUB_CODE != null ?
                new ObjectParameter("NEW_LOAD_UNIT_CONDITION_SUB_CODE", nEW_LOAD_UNIT_CONDITION_SUB_CODE) :
                new ObjectParameter("NEW_LOAD_UNIT_CONDITION_SUB_CODE", typeof(string));
    
            var vOID_SSCCParameter = vOID_SSCC != null ?
                new ObjectParameter("VOID_SSCC", vOID_SSCC) :
                new ObjectParameter("VOID_SSCC", typeof(string));
    
            var oLD_LOAD_CARRIER_EANParameter = oLD_LOAD_CARRIER_EAN != null ?
                new ObjectParameter("OLD_LOAD_CARRIER_EAN", oLD_LOAD_CARRIER_EAN) :
                new ObjectParameter("OLD_LOAD_CARRIER_EAN", typeof(string));
    
            var nEW_LOAD_CARRIER_EANParameter = nEW_LOAD_CARRIER_EAN != null ?
                new ObjectParameter("NEW_LOAD_CARRIER_EAN", nEW_LOAD_CARRIER_EAN) :
                new ObjectParameter("NEW_LOAD_CARRIER_EAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("API_INSERT_CHANGE", sSCCParameter, oRDER_NUMBERParameter, nEW_ORDER_NUMBERParameter, oLD_ACTORParameter, nEW_ACTORParameter, lOAD_MESSAGE_STATUS_IDParameter, uPDATE_DATEParameter, uPDATE_USERParameter, oLD_LOAD_UNIT_CONDITION_CODEParameter, nEW_LOAD_UNIT_CONDITION_CODEParameter, oLD_QTY_RTIParameter, eSOFT_PACKING_IDParameter, nEW_QTY_RTIParameter, dELETE_SSCCParameter, oLD_SSCCParameter, nEW_SSCCParameter, tRA_ITEM_IN_IDParameter, sLA_CODEParameter, tIMEParameter, vALIDATIONParameter, oLD_LOAD_UNIT_CONDITION_SUB_CODEParameter, nEW_LOAD_UNIT_CONDITION_SUB_CODEParameter, vOID_SSCCParameter, oLD_LOAD_CARRIER_EANParameter, nEW_LOAD_CARRIER_EANParameter);
        }
    }
}
