//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCC_DEL
    {
        public long SSCC_ID { get; set; }
        public string SSCC { get; set; }
        public Nullable<decimal> FIRST_SSCC_USAGE { get; set; }
        public Nullable<decimal> END_SSCC_USAGE { get; set; }
        public int SSCC_STATUS_ID { get; set; }
        public Nullable<int> LAST_TRANSACTION_ACTOR_ID { get; set; }
        public string LAST_TRANSACTION_DEVICE_CODE { get; set; }
        public Nullable<int> LAST_TRANSACTION_ACTION_ID { get; set; }
        public Nullable<decimal> LAST_TRANSACTION_DATE { get; set; }
        public string LAST_TRANSACTION_TIME { get; set; }
        public string LAST_TRANSACTION_TYPE_ID { get; set; }
        public int LAST_TRANSACTION_LOAD_UNIT_SLA_ID { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public string SHIPMENT_NUMBER { get; set; }
        public string SEAL_NUMBER { get; set; }
        public string LICENSE_PLATE { get; set; }
        public string CONFIRMATION { get; set; }
        public decimal ESOFT_TRANSACTION_ID { get; set; }
        public int NUMBER_SSCC_ON_ORDER { get; set; }
        public int LAST_STACKING_HEIGHT { get; set; }
        public int LAST_NUMBER_STACKS { get; set; }
        public int LAST_MEASURED_LENGTH { get; set; }
        public int LAST_MEASURED_WIDTH { get; set; }
        public int LAST_MEASURED_HEIGHT { get; set; }
        public int LAST_MEASURED_VOLUME { get; set; }
        public int LAST_MEASURED_WEIGHT { get; set; }
        public int LAST_ESTIMATED_SEU_MISSING { get; set; }
        public int LAST_RESULT_NUMBER_SEU { get; set; }
        public int DECICIVE_CI_DEVICE_ID { get; set; }
        public Nullable<decimal> DECICIVE_CI_DATE { get; set; }
        public string DECICIVE_CI_TIME { get; set; }
        public int DEC_TOT_QTY_RTI_COUNTED { get; set; }
        public decimal DEC_TOT_SEU_RECALCULATED { get; set; }
        public int DEC_TOT_WEIGHT_RTI_CALCULATED { get; set; }
        public int DEC_TOT_LOAD_UNIT_WEIGHT_CALCULATED { get; set; }
        public int DEC_TOT_VOLUME_RTI_CALCULATED { get; set; }
        public int DEC_TOT_LOAD_UNIT_VOLUME_CALCULATED { get; set; }
        public string CALC_INVOICE_ORDER_NUMBER { get; set; }
        public string CUSTOMER_REFERENCE { get; set; }
        public int SOURCE_REFERENCE_ID { get; set; }
        public string CALC_CONTRACT_ORDER { get; set; }
        public string CALC_CUSTOMER_REFERENCE { get; set; }
        public string CALC_RECEIPT_ID { get; set; }
        public int CALC_FROM_ACTOR_ID { get; set; }
        public int CALC_TO_ACTOR_ID { get; set; }
        public string STATUS { get; set; }
        public bool DECICIVE_CI_IND { get; set; }
        public string CALC_FINANCIAL_PARTNER { get; set; }
        public Nullable<int> CALC_LOGISTIC_PARTNER { get; set; }
        public string CALC_TRANSPORTER_ID { get; set; }
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public int ACTOR_ID_ORIGIN { get; set; }
        public int LAST_ACTOR_ID_STOCK { get; set; }
        public Nullable<long> LAST_TRANSACTION_ID { get; set; }
        public string LAST_SSCC_LOCATION { get; set; }
        public Nullable<decimal> FIRST_RECEIPT_DATE { get; set; }
        public Nullable<int> COUNTED_GRAI { get; set; }
        public Nullable<decimal> CALCULATED_HEIGHT { get; set; }
        public string FIRST_RECEIPT_TIME { get; set; }
        public Nullable<int> RCM_500_STATUS_ID { get; set; }
        public Nullable<int> RCM_419_STATUS_ID { get; set; }
        public Nullable<int> RCM_415_STATUS_ID { get; set; }
        public Nullable<int> SOURCE_REFERENCE_ID_RCM415 { get; set; }
        public string AUDIT_USER { get; set; }
        public System.DateTime AUDIT_TIMESTAMP { get; set; }
    }
}
