//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCC_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSCC_ORDER()
        {
            this.SSCC_MANAGEMENT = new HashSet<SSCC_MANAGEMENT>();
        }
    
        public long SSCC_ORDER_ID { get; set; }
        public int ACTOR_ORIGIN_ID { get; set; }
        public int ACTOR_DELIVERY_ID { get; set; }
        public int LOAD_UNIT_ID { get; set; }
        public int LOAD_UNIT_SLA_ID { get; set; }
        public int QTY_ORDER { get; set; }
        public string ORDERED_BY { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public bool SSCC_ORDER_IN_USE { get; set; }
        public string CARDBOARD_BOX { get; set; }
        public string SPLIT { get; set; }
        public string LABEL_TYPE { get; set; }
        public string PRINT_ORDER_CODE { get; set; }
        public string FIRST_SSCC { get; set; }
        public string LAST_SSCC { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    
        public virtual ACTOR_REFERENCE ACTOR_REFERENCE { get; set; }
        public virtual ACTOR_REFERENCE ACTOR_REFERENCE1 { get; set; }
        public virtual LOAD_UNIT LOAD_UNIT { get; set; }
        public virtual LOAD_UNIT_SLA LOAD_UNIT_SLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSCC_MANAGEMENT> SSCC_MANAGEMENT { get; set; }
    }
}
