//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_SSCC_RTI_GRAI
    {
        public long TRANSACTION_SSCC_RTI_GRAI_ID { get; set; }
        public long TRANSACTION_ID { get; set; }
        public string SSCC { get; set; }
        public int RTI_ID { get; set; }
        public string GRAI { get; set; }
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string COLUMN { get; set; }
        public Nullable<int> RTI_HEIGHT { get; set; }
        public Nullable<int> RTI_LENGTH { get; set; }
        public Nullable<int> RTI_WIDTH { get; set; }
        public string POSITION_X { get; set; }
        public string POSITION_Y { get; set; }
        public string POSITION_Z { get; set; }
    }
}
