//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_SUBTYPES
    {
        public int TRANSACTION_SUBTYPE_ID { get; set; }
        public string TRANSACTION_SUBTYPE { get; set; }
        public string TRANSACTION_TYPE_ID { get; set; }
        public int ACTOR_TYPE_ID { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
