//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSLATION_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSLATION_DETAILS()
        {
            this.ERROR_TRANSLATION = new HashSet<ERROR_TRANSLATION>();
            this.LOAD_CARRIER_TRANSLATION = new HashSet<LOAD_CARRIER_TRANSLATION>();
            this.LOAD_UNIT_CONDITION_TRANSLATION = new HashSet<LOAD_UNIT_CONDITION_TRANSLATION>();
            this.LOAD_UNIT_TRANSLATION = new HashSet<LOAD_UNIT_TRANSLATION>();
            this.SORTING_STATUS_TRANSLATION = new HashSet<SORTING_STATUS_TRANSLATION>();
        }
    
        public int TRANSLATION_ID { get; set; }
        public string LANGUAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ISO_639_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERROR_TRANSLATION> ERROR_TRANSLATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_CARRIER_TRANSLATION> LOAD_CARRIER_TRANSLATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_UNIT_CONDITION_TRANSLATION> LOAD_UNIT_CONDITION_TRANSLATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAD_UNIT_TRANSLATION> LOAD_UNIT_TRANSLATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORTING_STATUS_TRANSLATION> SORTING_STATUS_TRANSLATION { get; set; }
    }
}
