//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CI_WITHOUT_INBOUND
    {
        public string SSCC { get; set; }
        public string TRANSACTION_SUBTYPE { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public long TRA_ITEM_IN_ID { get; set; }
    }
}
