//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SSCC_VALIDATED_MT
    {
        public long TRANSACTION_ID { get; set; }
        public string SSCC { get; set; }
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
    }
}
