//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_LOAD_MESSAGE_STATUS
    {
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
        public string LOAD_MESSAGE_STATUS_NAME { get; set; }
        public string LOAD_MESSAGE_STATUS_DESCRIPTION { get; set; }
        public decimal LOAD_MESSAGE_STATUS_SORT { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
