//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_RPT_PROCESS_QTY
    {
        public long SRL_RPT_PROCESS_QTY_ID { get; set; }
        public Nullable<decimal> ORDER_ID { get; set; }
        public Nullable<decimal> ACTOR_ORIGIN_ID { get; set; }
        public Nullable<long> SSCC_ID { get; set; }
        public Nullable<int> RTI_ID { get; set; }
        public Nullable<int> CI_QTY_RTI { get; set; }
        public Nullable<System.DateTime> CI_MAX_UPDATE_DATE { get; set; }
        public Nullable<int> RA_QTY_RTI { get; set; }
        public Nullable<System.DateTime> RA_MAX_UPDATE_DATE { get; set; }
        public Nullable<int> TRX_QTY_RTI { get; set; }
        public Nullable<System.DateTime> TRX_MAX_UPDATE_DATE { get; set; }
        public Nullable<int> ORD_QTY_RTI { get; set; }
        public Nullable<System.DateTime> ORD_MAX_UPDATE_DATE { get; set; }
        public Nullable<int> MV_QTY_RTI { get; set; }
        public Nullable<System.DateTime> MV_MAX_UPDATE_DATE { get; set; }
        public string REPORT_LEVEL { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> L1_CI_TOTAL { get; set; }
        public Nullable<int> L1_RA_MINUS_CI_TOTAL { get; set; }
        public Nullable<int> RA_MINUS_ORD { get; set; }
        public Nullable<int> RA_MINUS_MV { get; set; }
        public string ORDER_NR { get; set; }
    }
}
