//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_DV_LOAD
    {
        public string SSCC { get; set; }
        public string RTI_EAN { get; set; }
        public string GRAI { get; set; }
        public Nullable<int> COLUMN { get; set; }
        public Nullable<int> RTI_HEIGHT { get; set; }
        public Nullable<int> RTI_LENGTH { get; set; }
        public Nullable<int> RTI_WIDTH { get; set; }
        public string POSITION_X { get; set; }
        public string POSITION_Y { get; set; }
        public string POSITION_Z { get; set; }
        public string COLOR_RED { get; set; }
        public string COLOR_GREEN { get; set; }
        public string COLOR_BLUE { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public int Z_STG_XML_DATA_ID { get; set; }
        public Nullable<int> Z_STG_XML_STATUS_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
    }
}
