//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_DV_TRANSACTION
    {
        public string SSCC { get; set; }
        public string TRANSACTION_DATE { get; set; }
        public string TRANSACTION_TIME { get; set; }
        public string TRANSACTION_TYPE_ID { get; set; }
        public string TRANSACTION_GMT_OFFSET { get; set; }
        public string ACTOR_ID { get; set; }
        public string SSCC_LOCATION { get; set; }
        public string LOCATION { get; set; }
        public string SEAL_ID { get; set; }
        public string SHIPMENT { get; set; }
        public string DEVICE_ID { get; set; }
        public string DEPOT_SSCC_LOCATION { get; set; }
        public string ORIGINAL_SSCC_LOCATION { get; set; }
        public string ORIGINAL_SSCC { get; set; }
        public string LICENSE_PLATE { get; set; }
        public string USER { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public int Z_STG_XML_DATA_ID { get; set; }
        public Nullable<int> Z_STG_XML_STATUS_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
        public Nullable<bool> IS_ANOMALY { get; set; }
    }
}
