//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_DV_PICTURES
    {
        public string SSCC { get; set; }
        public string PICTURE_PATH { get; set; }
        public string PICTURE_POSITION { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public int Z_STG_XML_DATA_ID { get; set; }
        public Nullable<int> Z_STG_XML_STATUS_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
    }
}
