//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_TRANSACTION_LOAD_UNIT_CONDITION
    {
        public long LINK_TRANSACTION_LOAD_UNIT_CONDITION_ID { get; set; }
        public long LOAD_UNIT_CONDITION_ID { get; set; }
        public long TRANSACTION_ID { get; set; }
        public Nullable<bool> CALCULATED { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public string LOAD_UNIT_CONDITION_SUB_CODE { get; set; }
    
        public virtual LOAD_UNIT_CONDITION LOAD_UNIT_CONDITION { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
