//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAD_UNIT_TRANSLATION
    {
        public int LOAD_UNIT_TRANSLATION_ID { get; set; }
        public int LOAD_UNIT_ID { get; set; }
        public int TRANSLATION_ID { get; set; }
        public string LOAD_UNIT_NAME { get; set; }
    
        public virtual LOAD_UNIT LOAD_UNIT { get; set; }
        public virtual TRANSLATION_DETAILS TRANSLATION_DETAILS { get; set; }
    }
}
