//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTI_TRANSLATION
    {
        public int RTI_TRANSLATION_ID { get; set; }
        public int RTI_ID { get; set; }
        public int TRANSLATION_ID { get; set; }
        public string RTI_NAME_SHORT { get; set; }
        public string RTI_NAME { get; set; }
    
        public virtual RTI_TRANSLATION RTI_TRANSLATION1 { get; set; }
        public virtual RTI_TRANSLATION RTI_TRANSLATION2 { get; set; }
    }
}
