//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SORTING_STATUS_TRANSLATION
    {
        public int SORTING_STATUS_ID { get; set; }
        public int SORTING_STATUS_TRANSLATION_ID { get; set; }
        public int TRANSLATION_ID { get; set; }
        public string SORTING_STATUS_NAME { get; set; }
    
        public virtual SORTING_STATUS SORTING_STATUS { get; set; }
        public virtual TRANSLATION_DETAILS TRANSLATION_DETAILS { get; set; }
    }
}
