//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BACKUP_SRL_20180613Entities : DbContext
    {
        public BACKUP_SRL_20180613Entities()
            : base("name=BACKUP_SRL_20180613Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTION> ACTION { get; set; }
        public virtual DbSet<ACTOR_LABEL_DETAILS> ACTOR_LABEL_DETAILS { get; set; }
        public virtual DbSet<ACTOR_REFERENCE> ACTOR_REFERENCE { get; set; }
        public virtual DbSet<ACTOR_TYPE> ACTOR_TYPE { get; set; }
        public virtual DbSet<AUDIT> AUDIT { get; set; }
        public virtual DbSet<CONTENT> CONTENT { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS> CPF_SOURCE_REFERENCE_SLRS { get; set; }
        public virtual DbSet<DEPOT_LABEL> DEPOT_LABEL { get; set; }
        public virtual DbSet<DEVIATION_BY_RETAILER> DEVIATION_BY_RETAILER { get; set; }
        public virtual DbSet<ERROR> ERROR { get; set; }
        public virtual DbSet<ERROR_HANDLING> ERROR_HANDLING { get; set; }
        public virtual DbSet<ERROR_HANDLING_ARCHIVE> ERROR_HANDLING_ARCHIVE { get; set; }
        public virtual DbSet<ERROR_TRANSLATION> ERROR_TRANSLATION { get; set; }
        public virtual DbSet<ESOFT_API_RCM500> ESOFT_API_RCM500 { get; set; }
        public virtual DbSet<INPUT_SSCC_MANAGEMENT> INPUT_SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<INTERFACING> INTERFACING { get; set; }
        public virtual DbSet<LATE_TRANSACTIONS> LATE_TRANSACTIONS { get; set; }
        public virtual DbSet<LINK_TRANSACTION_LOAD_UNIT_CONDITION> LINK_TRANSACTION_LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_CARRIER> LOAD_CARRIER { get; set; }
        public virtual DbSet<LOAD_CARRIER_TRANSLATION> LOAD_CARRIER_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT> LOAD_UNIT { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION> LOAD_UNIT_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_CONDITION_TRANSLATION> LOAD_UNIT_CONDITION_TRANSLATION { get; set; }
        public virtual DbSet<LOAD_UNIT_SLA> LOAD_UNIT_SLA { get; set; }
        public virtual DbSet<LOAD_UNIT_SUB_CONDITION> LOAD_UNIT_SUB_CONDITION { get; set; }
        public virtual DbSet<LOAD_UNIT_TRANSLATION> LOAD_UNIT_TRANSLATION { get; set; }
        public virtual DbSet<PICTURE_EVIDENCE> PICTURE_EVIDENCE { get; set; }
        public virtual DbSet<REF_ORDER> REF_ORDER { get; set; }
        public virtual DbSet<REF_TRANSACTION_TEMP_RECEIPTS> REF_TRANSACTION_TEMP_RECEIPTS { get; set; }
        public virtual DbSet<REPORTING_ACTOR_TYPE> REPORTING_ACTOR_TYPE { get; set; }
        public virtual DbSet<RETAILER_CHAIN> RETAILER_CHAIN { get; set; }
        public virtual DbSet<RT_TYPE> RT_TYPE { get; set; }
        public virtual DbSet<RTI> RTI { get; set; }
        public virtual DbSet<RTI_ACCEPTANCE> RTI_ACCEPTANCE { get; set; }
        public virtual DbSet<RTI_TRANSLATION> RTI_TRANSLATION { get; set; }
        public virtual DbSet<SHIPMENT> SHIPMENT { get; set; }
        public virtual DbSet<SORTING_STATUS> SORTING_STATUS { get; set; }
        public virtual DbSet<SORTING_STATUS_TRANSLATION> SORTING_STATUS_TRANSLATION { get; set; }
        public virtual DbSet<SSCC> SSCC { get; set; }
        public virtual DbSet<SSCC_DEL> SSCC_DEL { get; set; }
        public virtual DbSet<SSCC_MANAGEMENT> SSCC_MANAGEMENT { get; set; }
        public virtual DbSet<SSCC_ORDER> SSCC_ORDER { get; set; }
        public virtual DbSet<SSCC_RTI_DETAILS> SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<SSCC_RTI_GRAI> SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<STANDARD_DISTRIBUTION> STANDARD_DISTRIBUTION { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIMEONSITE> TIMEONSITE { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTION { get; set; }
        public virtual DbSet<TRANSACTION_DEL> TRANSACTION_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS> TRANSACTION_SSCC_RTI_DETAILS { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_DEL> TRANSACTION_SSCC_RTI_DETAILS_DEL { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF> TRANSACTION_SSCC_RTI_DETAILS_QTY_DIF { get; set; }
        public virtual DbSet<TRANSACTION_SSCC_RTI_GRAI> TRANSACTION_SSCC_RTI_GRAI { get; set; }
        public virtual DbSet<TRANSACTION_SUBTYPES> TRANSACTION_SUBTYPES { get; set; }
        public virtual DbSet<TRANSLATION_DETAILS> TRANSLATION_DETAILS { get; set; }
        public virtual DbSet<XML_EXPORT_MESSAGES> XML_EXPORT_MESSAGES { get; set; }
        public virtual DbSet<Z_CHANGES_TO_DATABASE> Z_CHANGES_TO_DATABASE { get; set; }
        public virtual DbSet<Z_LOAD_MESSAGE_STATUS> Z_LOAD_MESSAGE_STATUS { get; set; }
        public virtual DbSet<Z_SSCC_NUMBERS> Z_SSCC_NUMBERS { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_NUMBER> Z_SSCC_ORDER_NUMBER { get; set; }
        public virtual DbSet<Z_SSCC_ORDER_RETAILER_DETAILS> Z_SSCC_ORDER_RETAILER_DETAILS { get; set; }
        public virtual DbSet<Z_STG_XML_ANOMALIES> Z_STG_XML_ANOMALIES { get; set; }
        public virtual DbSet<Z_STG_XML_CONTENT> Z_STG_XML_CONTENT { get; set; }
        public virtual DbSet<Z_STG_XML_COUNTING> Z_STG_XML_COUNTING { get; set; }
        public virtual DbSet<Z_STG_XML_DATA> Z_STG_XML_DATA { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD> Z_STG_XML_LOAD { get; set; }
        public virtual DbSet<Z_STG_XML_LOAD_CARRIER> Z_STG_XML_LOAD_CARRIER { get; set; }
        public virtual DbSet<Z_STG_XML_ORDER> Z_STG_XML_ORDER { get; set; }
        public virtual DbSet<Z_STG_XML_PICTURES> Z_STG_XML_PICTURES { get; set; }
        public virtual DbSet<Z_STG_XML_SHIPMENT> Z_STG_XML_SHIPMENT { get; set; }
        public virtual DbSet<Z_STG_XML_TIMEONSITE> Z_STG_XML_TIMEONSITE { get; set; }
        public virtual DbSet<Z_STG_XML_TRANSACTION> Z_STG_XML_TRANSACTION { get; set; }
        public virtual DbSet<Z_VALIDATION> Z_VALIDATION { get; set; }
        public virtual DbSet<CPF_410_AGGREGATED_ACTOR_CODE> CPF_410_AGGREGATED_ACTOR_CODE { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_NEW> CPF_SOURCE_REFERENCE_SLRS_NEW { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM410> CPF_SOURCE_REFERENCE_SLRS_RCM410 { get; set; }
        public virtual DbSet<CPF_SOURCE_REFERENCE_SLRS_RCM415> CPF_SOURCE_REFERENCE_SLRS_RCM415 { get; set; }
        public virtual DbSet<PARAMETER_SRLS> PARAMETER_SRLS { get; set; }
        public virtual DbSet<PARAMETER_SRLS_NEW> PARAMETER_SRLS_NEW { get; set; }
        public virtual DbSet<REF_ORDER_UPSERT> REF_ORDER_UPSERT { get; set; }
        public virtual DbSet<RTI_DATASET> RTI_DATASET { get; set; }
        public virtual DbSet<RUNNING_JOB_CHECK> RUNNING_JOB_CHECK { get; set; }
    
        [DbFunction("BACKUP_SRL_20180613Entities", "API_FN_SPLIT")]
        public virtual IQueryable<API_FN_SPLIT_Result> API_FN_SPLIT(string tEXT, string dELIMITER)
        {
            var tEXTParameter = tEXT != null ?
                new ObjectParameter("TEXT", tEXT) :
                new ObjectParameter("TEXT", typeof(string));
    
            var dELIMITERParameter = dELIMITER != null ?
                new ObjectParameter("DELIMITER", dELIMITER) :
                new ObjectParameter("DELIMITER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<API_FN_SPLIT_Result>("[BACKUP_SRL_20180613Entities].[API_FN_SPLIT](@TEXT, @DELIMITER)", tEXTParameter, dELIMITERParameter);
        }
    
        public virtual ObjectResult<API_LIST_ACTORS_TRANSACTION_Result> API_LIST_ACTORS_TRANSACTION(Nullable<int> rETAILER_CHAIN_ID)
        {
            var rETAILER_CHAIN_IDParameter = rETAILER_CHAIN_ID.HasValue ?
                new ObjectParameter("RETAILER_CHAIN_ID", rETAILER_CHAIN_ID) :
                new ObjectParameter("RETAILER_CHAIN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<API_LIST_ACTORS_TRANSACTION_Result>("API_LIST_ACTORS_TRANSACTION", rETAILER_CHAIN_IDParameter);
        }
    
        public virtual ObjectResult<API_SSCC_OVERVIEW_Result> API_SSCC_OVERVIEW(string aCTOR_ID, string aCTOR_ORIGIN_ID, Nullable<bool> sSCC_STATUS_NEW, Nullable<bool> sSCC_STATUS_PROCESSED, Nullable<bool> sSCC_STATUS_VALIDATED, Nullable<System.DateTime> fIRST_SSCC_USAGE_FROM, Nullable<System.DateTime> fIRST_SSCC_USAGE_TO, Nullable<System.DateTime> cI_DATETIME_FROM, Nullable<System.DateTime> cI_DATETIME_TO, Nullable<bool> vALIDATION_DEADLINE_OPEN, Nullable<bool> vALIDATION_DEADLINE_EXCEEDED, Nullable<bool> vALIDATION_DEADLINE_PASSED, string sSCC, Nullable<decimal> oRDER_NUMBER, Nullable<bool> cOUNTING_OK, Nullable<bool> cOUNTING_NOK, Nullable<bool> sLA_OK, Nullable<bool> sLA_NOK, Nullable<int> rETAILER_CHAIN_ID)
        {
            var aCTOR_IDParameter = aCTOR_ID != null ?
                new ObjectParameter("ACTOR_ID", aCTOR_ID) :
                new ObjectParameter("ACTOR_ID", typeof(string));
    
            var aCTOR_ORIGIN_IDParameter = aCTOR_ORIGIN_ID != null ?
                new ObjectParameter("ACTOR_ORIGIN_ID", aCTOR_ORIGIN_ID) :
                new ObjectParameter("ACTOR_ORIGIN_ID", typeof(string));
    
            var sSCC_STATUS_NEWParameter = sSCC_STATUS_NEW.HasValue ?
                new ObjectParameter("SSCC_STATUS_NEW", sSCC_STATUS_NEW) :
                new ObjectParameter("SSCC_STATUS_NEW", typeof(bool));
    
            var sSCC_STATUS_PROCESSEDParameter = sSCC_STATUS_PROCESSED.HasValue ?
                new ObjectParameter("SSCC_STATUS_PROCESSED", sSCC_STATUS_PROCESSED) :
                new ObjectParameter("SSCC_STATUS_PROCESSED", typeof(bool));
    
            var sSCC_STATUS_VALIDATEDParameter = sSCC_STATUS_VALIDATED.HasValue ?
                new ObjectParameter("SSCC_STATUS_VALIDATED", sSCC_STATUS_VALIDATED) :
                new ObjectParameter("SSCC_STATUS_VALIDATED", typeof(bool));
    
            var fIRST_SSCC_USAGE_FROMParameter = fIRST_SSCC_USAGE_FROM.HasValue ?
                new ObjectParameter("FIRST_SSCC_USAGE_FROM", fIRST_SSCC_USAGE_FROM) :
                new ObjectParameter("FIRST_SSCC_USAGE_FROM", typeof(System.DateTime));
    
            var fIRST_SSCC_USAGE_TOParameter = fIRST_SSCC_USAGE_TO.HasValue ?
                new ObjectParameter("FIRST_SSCC_USAGE_TO", fIRST_SSCC_USAGE_TO) :
                new ObjectParameter("FIRST_SSCC_USAGE_TO", typeof(System.DateTime));
    
            var cI_DATETIME_FROMParameter = cI_DATETIME_FROM.HasValue ?
                new ObjectParameter("CI_DATETIME_FROM", cI_DATETIME_FROM) :
                new ObjectParameter("CI_DATETIME_FROM", typeof(System.DateTime));
    
            var cI_DATETIME_TOParameter = cI_DATETIME_TO.HasValue ?
                new ObjectParameter("CI_DATETIME_TO", cI_DATETIME_TO) :
                new ObjectParameter("CI_DATETIME_TO", typeof(System.DateTime));
    
            var vALIDATION_DEADLINE_OPENParameter = vALIDATION_DEADLINE_OPEN.HasValue ?
                new ObjectParameter("VALIDATION_DEADLINE_OPEN", vALIDATION_DEADLINE_OPEN) :
                new ObjectParameter("VALIDATION_DEADLINE_OPEN", typeof(bool));
    
            var vALIDATION_DEADLINE_EXCEEDEDParameter = vALIDATION_DEADLINE_EXCEEDED.HasValue ?
                new ObjectParameter("VALIDATION_DEADLINE_EXCEEDED", vALIDATION_DEADLINE_EXCEEDED) :
                new ObjectParameter("VALIDATION_DEADLINE_EXCEEDED", typeof(bool));
    
            var vALIDATION_DEADLINE_PASSEDParameter = vALIDATION_DEADLINE_PASSED.HasValue ?
                new ObjectParameter("VALIDATION_DEADLINE_PASSED", vALIDATION_DEADLINE_PASSED) :
                new ObjectParameter("VALIDATION_DEADLINE_PASSED", typeof(bool));
    
            var sSCCParameter = sSCC != null ?
                new ObjectParameter("SSCC", sSCC) :
                new ObjectParameter("SSCC", typeof(string));
    
            var oRDER_NUMBERParameter = oRDER_NUMBER.HasValue ?
                new ObjectParameter("ORDER_NUMBER", oRDER_NUMBER) :
                new ObjectParameter("ORDER_NUMBER", typeof(decimal));
    
            var cOUNTING_OKParameter = cOUNTING_OK.HasValue ?
                new ObjectParameter("COUNTING_OK", cOUNTING_OK) :
                new ObjectParameter("COUNTING_OK", typeof(bool));
    
            var cOUNTING_NOKParameter = cOUNTING_NOK.HasValue ?
                new ObjectParameter("COUNTING_NOK", cOUNTING_NOK) :
                new ObjectParameter("COUNTING_NOK", typeof(bool));
    
            var sLA_OKParameter = sLA_OK.HasValue ?
                new ObjectParameter("SLA_OK", sLA_OK) :
                new ObjectParameter("SLA_OK", typeof(bool));
    
            var sLA_NOKParameter = sLA_NOK.HasValue ?
                new ObjectParameter("SLA_NOK", sLA_NOK) :
                new ObjectParameter("SLA_NOK", typeof(bool));
    
            var rETAILER_CHAIN_IDParameter = rETAILER_CHAIN_ID.HasValue ?
                new ObjectParameter("RETAILER_CHAIN_ID", rETAILER_CHAIN_ID) :
                new ObjectParameter("RETAILER_CHAIN_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<API_SSCC_OVERVIEW_Result>("API_SSCC_OVERVIEW", aCTOR_IDParameter, aCTOR_ORIGIN_IDParameter, sSCC_STATUS_NEWParameter, sSCC_STATUS_PROCESSEDParameter, sSCC_STATUS_VALIDATEDParameter, fIRST_SSCC_USAGE_FROMParameter, fIRST_SSCC_USAGE_TOParameter, cI_DATETIME_FROMParameter, cI_DATETIME_TOParameter, vALIDATION_DEADLINE_OPENParameter, vALIDATION_DEADLINE_EXCEEDEDParameter, vALIDATION_DEADLINE_PASSEDParameter, sSCCParameter, oRDER_NUMBERParameter, cOUNTING_OKParameter, cOUNTING_NOKParameter, sLA_OKParameter, sLA_NOKParameter, rETAILER_CHAIN_IDParameter);
        }
    }
}
