//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCC_RTI_GRAI
    {
        public long SSCC_RTI_GRAI_ID { get; set; }
        public string SSCC { get; set; }
        public Nullable<decimal> FIRST_SSCC_USAGE { get; set; }
        public int RTI_ID { get; set; }
        public string GRAI { get; set; }
        public System.DateTime CI_DATE { get; set; }
        public System.DateTime CI_TIME { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string GRA_POSITION { get; set; }
    }
}
