//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XML_EXPORT_MESSAGES
    {
        public long ID { get; set; }
        public string SSCC { get; set; }
        public long TRA_ITEM_IN_ID { get; set; }
        public string XMLDATA { get; set; }
        public string XMLNAME { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public Nullable<System.DateTime> MESSAGE_DATE { get; set; }
        public Nullable<System.DateTime> EXPORT_DATE { get; set; }
        public string MESSAGE_TYPE { get; set; }
    }
}
