//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_SSCC_ORDER_NUMBER
    {
        public int SSCC_ORDER_NUMBER_ID { get; set; }
        public string actor { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<byte> LOAD_MESSAGE_STATUS_ID { get; set; }
        public int QTY_ORDERNUMBER { get; set; }
        public string SSCC_RESERVED { get; set; }
        public Nullable<long> SSCC_RESERVED_NUMBER { get; set; }
        public Nullable<int> MAX_SSCC { get; set; }
        public Nullable<bool> IND_MAX_SSCC_REACHED { get; set; }
        public Nullable<bool> IND_SSCC_RETIRED { get; set; }
    }
}
