//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_LOAD_CARRIER
    {
        public long Z_STG_XML_LOAD_CARRIER_ID { get; set; }
        public string SSCC { get; set; }
        public Nullable<decimal> LOAD_CARRIER_EAN { get; set; }
        public Nullable<int> NUMBER_STACKS { get; set; }
        public string LOAD_UNIT_CODE { get; set; }
        public Nullable<int> LOAD_CARRIER_LENGTH { get; set; }
        public Nullable<int> LOAD_CARRIER_WIDTH { get; set; }
        public Nullable<int> LOAD_CARRIER_HEIGHT { get; set; }
        public Nullable<int> LOAD_CARRIER_VOLUME { get; set; }
        public Nullable<int> LOAD_CARRIER_WEIGHT { get; set; }
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<decimal> XML_ITEM_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
        public string GRAI { get; set; }
        public string LOAD_UNIT_TOKEN { get; set; }
        public Nullable<int> CALCULATED_EAN_CODE { get; set; }
    }
}
