//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_COUNTING
    {
        public long Z_STG_XML_COUNTING_ID { get; set; }
        public string SSCC { get; set; }
        public Nullable<decimal> RTI_EAN { get; set; }
        public Nullable<decimal> RT_QUANTITY { get; set; }
        public Nullable<int> LOAD_MESSAGE_STATUS_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<decimal> XML_ITEM_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
        public Nullable<int> RT_TYPE_ID { get; set; }
        public string UNIT { get; set; }
    }
}
