//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL_Portal_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_STG_XML_ORDER
    {
        public long Z_STG_XML_ORDER_ID { get; set; }
        public string SSCC { get; set; }
        public Nullable<int> NUMBER_SSCC_ON_ORDER { get; set; }
        public Nullable<decimal> ORDER_NUMBER { get; set; }
        public int LOAD_MESSAGE_STATUS_ID { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public Nullable<decimal> XML_ITEM_ID { get; set; }
        public Nullable<long> TRA_ITEM_IN_ID { get; set; }
        public bool CLOSE_ORDER { get; set; }
        public string DEPOT_ORDER_NUMBER { get; set; }
        public string CUSTREF { get; set; }
        public Nullable<bool> MONO_SSCC_TRAILER { get; set; }
    }
}
