//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.Data_Access.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderStatuses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStatuses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRL.Data_Access.Resources.OrderStatuses", typeof(OrderStatuses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string OrderStatus_1 {
            get {
                return ResourceManager.GetString("OrderStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial check.
        /// </summary>
        internal static string OrderStatus_13 {
            get {
                return ResourceManager.GetString("OrderStatus_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string OrderStatus_14 {
            get {
                return ResourceManager.GetString("OrderStatus_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped via receipt.
        /// </summary>
        internal static string OrderStatus_15 {
            get {
                return ResourceManager.GetString("OrderStatus_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing ok.
        /// </summary>
        internal static string OrderStatus_16 {
            get {
                return ResourceManager.GetString("OrderStatus_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string OrderStatus_17 {
            get {
                return ResourceManager.GetString("OrderStatus_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be invoiced.
        /// </summary>
        internal static string OrderStatus_18 {
            get {
                return ResourceManager.GetString("OrderStatus_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only unloaded.
        /// </summary>
        internal static string OrderStatus_19 {
            get {
                return ResourceManager.GetString("OrderStatus_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract reject.
        /// </summary>
        internal static string OrderStatus_2 {
            get {
                return ResourceManager.GetString("OrderStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFR registration.
        /// </summary>
        internal static string OrderStatus_20 {
            get {
                return ResourceManager.GetString("OrderStatus_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial reject.
        /// </summary>
        internal static string OrderStatus_3 {
            get {
                return ResourceManager.GetString("OrderStatus_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial ok.
        /// </summary>
        internal static string OrderStatus_4 {
            get {
                return ResourceManager.GetString("OrderStatus_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic ok.
        /// </summary>
        internal static string OrderStatus_5 {
            get {
                return ResourceManager.GetString("OrderStatus_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic reject.
        /// </summary>
        internal static string OrderStatus_6 {
            get {
                return ResourceManager.GetString("OrderStatus_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string OrderStatus_7 {
            get {
                return ResourceManager.GetString("OrderStatus_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced.
        /// </summary>
        internal static string OrderStatus_8 {
            get {
                return ResourceManager.GetString("OrderStatus_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected.
        /// </summary>
        internal static string OrderStatus_9 {
            get {
                return ResourceManager.GetString("OrderStatus_9", resourceCulture);
            }
        }
    }
}
